version: '3'

services:
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    restart: always
    environment:

      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_BUCKET=dennis-bucket
      - DOCKER_INFLUXDB_INIT_USERNAME=dennis
      - DOCKER_INFLUXDB_INIT_PASSWORD=Bonjov123
      - DOCKER_INFLUXDB_INIT_ORG=dennis-org

    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2

  telegraf:
    image: telegraf
    container_name: telegraf
    user: root
    restart: always
    entrypoint: /bin/bash -c "chmod 777 /var/run/docker.sock && /entrypoint.sh telegraf"
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/hostfs:ro
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data: